- hosts: localhost
  tasks:
  - name: Prepare the mon group in the inventory
    add_host:
      name: "{{item}}"
      groups: mons
    with_items: 
      - "{{ single_node }}"
  - name: Prepare the osds group in the inventory
    add_host:
      name: "{{item}}"
      groups: osds
    with_items: 
      - "{{ single_node }}"
  - name: Prepare the mgrs group in the inventory
    add_host:
      name: "{{item}}"
      groups: mgrs
    with_items: 
      - "{{ single_node }}"
- import_playbook: site.yml 
